In [1]:
import torch

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [4]:
a = torch.rand(3,4,5)
a

tensor([[[0.3967, 0.0212, 0.4033, 0.3140, 0.8961],
         [0.3038, 0.8971, 0.0464, 0.2262, 0.4240],
         [0.4407, 0.1330, 0.7424, 0.3144, 0.5404],
         [0.0763, 0.3616, 0.1584, 0.9024, 0.0875]],

        [[0.5483, 0.6905, 0.4540, 0.2948, 0.9079],
         [0.1588, 0.8341, 0.0450, 0.1350, 0.0404],
         [0.0348, 0.8359, 0.5758, 0.5633, 0.0915],
         [0.9686, 0.6907, 0.2895, 0.1252, 0.9796]],

        [[0.2475, 0.4041, 0.4372, 0.5443, 0.2275],
         [0.6136, 0.9811, 0.0880, 0.2057, 0.8759],
         [0.2951, 0.9073, 0.4146, 0.2233, 0.0455],
         [0.1636, 0.1227, 0.2408, 0.7507, 0.1792]]])

In [5]:
a.type()

'torch.FloatTensor'

In [ ]:
# 2. Выведите его форму (shape)

In [6]:
a.shape

torch.Size([3, 4, 5])

In [ ]:
# 3. Приведите его к форме 6х10

In [18]:
a = a.reshape(6,10)
a

tensor([[0.3967, 0.0212, 0.4033, 0.3140, 0.8961, 0.3038, 0.8971, 0.0464, 0.2262,
         0.4240],
        [0.4407, 0.1330, 0.7424, 0.3144, 0.5404, 0.0763, 0.3616, 0.1584, 0.9024,
         0.0875],
        [0.5483, 0.6905, 0.4540, 0.2948, 0.9079, 0.1588, 0.8341, 0.0450, 0.1350,
         0.0404],
        [0.0348, 0.8359, 0.5758, 0.5633, 0.0915, 0.9686, 0.6907, 0.2895, 0.1252,
         0.9796],
        [0.2475, 0.4041, 0.4372, 0.5443, 0.2275, 0.6136, 0.9811, 0.0880, 0.2057,
         0.8759],
        [0.2951, 0.9073, 0.4146, 0.2233, 0.0455, 0.1636, 0.1227, 0.2408, 0.7507,
         0.1792]])

In [ ]:
# 4. Создайте случайный IntTensor размера 10

In [13]:
b = torch.IntTensor(10)
b

tensor([ 725800704,      21919,         27,          0,         -1,          0,
         678913390, 1142959146, 1667855973, 1679834981], dtype=torch.int32)

In [14]:
b.size()

torch.Size([10])

In [ ]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [22]:
c = a * b
c

tensor([[ 2.8789e+08,  4.6395e+02,  1.0889e+01,  0.0000e+00, -8.9605e-01,
          0.0000e+00,  6.0908e+08,  5.2988e+07,  3.7723e+08,  7.1219e+08],
        [ 3.1986e+08,  2.9155e+03,  2.0045e+01,  0.0000e+00, -5.4037e-01,
          0.0000e+00,  2.4550e+08,  1.8106e+08,  1.5051e+09,  1.4704e+08],
        [ 3.9798e+08,  1.5135e+04,  1.2258e+01,  0.0000e+00, -9.0785e-01,
          0.0000e+00,  5.6628e+08,  5.1472e+07,  2.2520e+08,  6.7897e+07],
        [ 2.5289e+07,  1.8322e+04,  1.5546e+01,  0.0000e+00, -9.1513e-02,
          0.0000e+00,  4.6894e+08,  3.3089e+08,  2.0876e+08,  1.6455e+09],
        [ 1.7964e+08,  8.8580e+03,  1.1804e+01,  0.0000e+00, -2.2750e-01,
          0.0000e+00,  6.6608e+08,  1.0057e+08,  3.4313e+08,  1.4714e+09],
        [ 2.1415e+08,  1.9888e+04,  1.1193e+01,  0.0000e+00, -4.5500e-02,
          0.0000e+00,  8.3300e+07,  2.7517e+08,  1.2520e+09,  3.0107e+08]])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [46]:
d = c @ c.T
d

tensor([[1.1062e+18, 9.2368e+17, 5.9552e+17, 1.5611e+18, 1.6401e+18, 8.1368e+17],
        [9.2368e+17, 2.4822e+18, 6.2456e+17, 7.3927e+17, 9.7196e+17, 2.0674e+18],
        [5.9552e+17, 6.2456e+17, 5.3704e+17, 4.5139e+17, 6.3103e+17, 4.4895e+17],
        [1.5611e+18, 7.3927e+17, 4.5139e+17, 3.0814e+18, 2.8430e+18, 8.9232e+17],
        [1.6401e+18, 9.7196e+17, 6.3103e+17, 2.8430e+18, 2.7687e+18, 9.9421e+17],
        [8.1368e+17, 2.0674e+18, 4.4895e+17, 8.9232e+17, 9.9421e+17, 1.7866e+18]])

In [47]:
d.size()

torch.Size([6, 6])

Второй способ

In [51]:
d = torch.matmul(c, c.T)
d

tensor([[1.1062e+18, 9.2368e+17, 5.9552e+17, 1.5611e+18, 1.6401e+18, 8.1368e+17],
        [9.2368e+17, 2.4822e+18, 6.2456e+17, 7.3927e+17, 9.7196e+17, 2.0674e+18],
        [5.9552e+17, 6.2456e+17, 5.3704e+17, 4.5139e+17, 6.3103e+17, 4.4895e+17],
        [1.5611e+18, 7.3927e+17, 4.5139e+17, 3.0814e+18, 2.8430e+18, 8.9232e+17],
        [1.6401e+18, 9.7196e+17, 6.3103e+17, 2.8430e+18, 2.7687e+18, 9.9421e+17],
        [8.1368e+17, 2.0674e+18, 4.4895e+17, 8.9232e+17, 9.9421e+17, 1.7866e+18]])

In [52]:
d.size()

torch.Size([6, 6])

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

т.к. в функции 3 переменных, можем найти их частные производные

Частная производная по x

In [ ]:
y_x = 3 * x + 0 - 0 = 3 * 1 = 3

Частная производная по z

In [ ]:
y_z = 0 + 1 - 0 = 1

Частная производная по t

In [ ]:
y_t = 0 + 0 - 75 = -75

Почитаем градиенты с помощью инструментов pytorch

In [71]:
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)

In [72]:
y = x**3 + z - 75*t

In [73]:
y.backward(x, z, t)


In [80]:
print(f'x_grad = {x.grad}')
print(f'z_grad = {z.grad}')
print(f't_grad = {t.grad}')

x_grad = tensor([3.], grad_fn=<CopyBackwards>)
z_grad = tensor([1.], grad_fn=<CopyBackwards>)
t_grad = tensor([-75.], grad_fn=<CopyBackwards>)


In [ ]:
# 8. Создайте единичный тензор размера 5x6

In [87]:
e = torch.ones((5,6))
e

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# 9. Переведите его в формат numpy

In [88]:
e.type()

'torch.FloatTensor'

In [89]:
e = e.numpy()
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [92]:
type(e)

numpy.ndarray